schema_version = "1.0.0"

id = "autosolve"
name = "AutoSolve"
version = "0.1.1"
tagline = "One-click automated camera tracking for Blender"
maintainer = "Usama Bin Shahid <usamasq@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"
blender_version_max = "6.0.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Usama Bin Shahid"]

[permissions]
files = "Access movie clip data for tracking"
